// Catálogo de materiales de los maletines, extraído de los listados oficiales
// UCP-IM-001 (enfermeras) y UCP-IM-002 (médicos)

// Categorías que requieren control de caducidad (medicación + sueros + desinfectantes)
window.EXPIRY_CATEGORIES = new Set([
  // Médicos
  'Respiratorio (Med)', 'Oftálmico', 'Opiáceos / BZD / Neurolépticos',
  'Analgesia / Corticoides / Procinéticos / Antieméticos',
  'Vía endovenosa (Opiáceos/BZD/Neurolépticos)', 'Vía endovenosa (Varios)',
  // Enfermería
  'Sueros', 'Pomadas', 'Medicación I/V',
  // Compartidos / Parenteral con desinfectantes
  'Parenteral - Desinfectantes',
]);

// Catálogo MÉDICO
window.CATALOG_MEDICO = [
  { section: 'Exploración', items: [
    'Fonendo (1U)',
    'Boli (1U), rotulador (1U)',
    'Pulsioxímetro (1U), sensor (2U) + TA',
    'Otoscopio (1U), conos gruesos y finos (10U x tamaño)',
    'Asas ORL (1)',
    'Oftalmoscopio (1U)',
    'Martillo reflejos (1U)',
    'Cinta métrica (1)',
    'Depresores (10U)',
    'Frontal (1U)',
    'Termómetro (1U)',
    'Guantes no estériles (10U)',
    'Mascarilla quirúrgica (5U)',
    'Batas desechables (2U)',
    'Pilas AA, AAA, botón CR2032 (4U)',
    'Hidroalcohol (1U)',
  ]},
  { section: 'Respiratorio (Med)', items: [
    'Cono adaptador de Oxígeno',
    'Salbutamol 2.5 mg (10U)',
    'Salbutamol 5 mg (10U)',
    'Budesonida (5U)',
    'Bromuro ipratropio 250mcg ampolla (10U)',
    'Bromuro ipratropio 500mcg (10U)',
    'Salbutamol puff (1U)',
    'Bromuro ipratropio (Atrovent) puff (1U)',
    'Budesonida puff (1U)',
    'Cámara administración y mascarilla (1U)',
    'Cánula de Yankauer (1)',
    'Paidocort (1U)',
    'Cloruro sódico 20% 10 ml (2U)',
    'Sondas de aspiración 10 / 12 (1U)',
    'Gafas Nasales',
    'Mascarilla Aerosoles',
    'Reservorio',
  ]},
  { section: 'Curas', items: [
    'Paño estéril (1U)',
    'Gasas estériles (6U)',
    'Guantes estériles 6.5 (2U); 7 (2)',
    'Tapón nasal (1U)',
    'Apósito transparente (1U)',
    'Apósito gasa (2U)',
    'Puntos aproximación (1U)',
    'Seda con aguja recta (2)',
    'Pinzas (1U)',
    'Bisturí (1U)',
    'Tijeras (1U)',
    'Esparadrapo (1U)',
    'Bolsas para residuos (5U)',
    'Lidocaína al 1% (2U)',
    'Sonda vesical intermitente 16 (1U) y 18 (1U)',
    'Lubricante urológico (1)',
  ]},
  { section: 'Canalización vías', items: [
    'Compresor',
    'Aguja endovenoso 22G, 24G (2U x tamaño)',
    'Agujas intramuscular (4U)',
    'Agujas subcutánea (3U)',
    'Agujas porta (2U)',
    'Vía subcutánea (1U)',
    'Aguja carga (3U)',
    'Jeringas 1cc, 5cc, 10cc (5U x tamaño)',
    'Pulverizador nasal (2U)',
    'Agua destilada (5U)',
    'Paquetes de suero (5U)',
    'Heparina (2U)',
    'Suero 50cc (2U)',
    'Llave de tres pasos (1)',
    'Alargadera (2)',
    'Apósitos fijación vías',
    'SNG núm. 8 (1U)',
    'Sistema de suero (2)',
    'Infusores (2)',
    'Cloruro de etilo (1)',
  ]},
  { section: 'Oftálmico', items: [
    'Fluoresceína (4U)',
    'Hipomelosa (Acuolens) (1U)',
    'Tobrex (1U)',
    'SF 0.9% (5U)',
    'Lipolasic',
  ]},
  { section: 'Impresos', items: [
    'Recetas Selladas',
    'Certificados de defunción (5U)',
    'Hoja Medicación (5U)',
    'Cuartillas papel (10U)',
    'Tarjetas (5U)',
  ]},
  { section: 'Opiáceos / BZD / Neurolépticos', items: [
    'Fentanilo citrato (Abstral) 100mcg (10U)',
    'Sulfato de morfina (Sevredol) 5mg (10U)',
    'Sulfato de morfina (Oramorph) 2mg/ml (1U)',
    'Diazepam gotas (1U)',
    'Diazepam 5mg (10U)',
    'Lorazepam (Orfidal) 1mg (5U)',
    'Diazepam (Stesolid) 5mg (5U)',
    'Diazepam (Stesolid) 10mg (5U)',
    'Haloperidol gotas (1U)',
    'Clorpromacina (Largactil) gotas (1U)',
    'Fentanilo (Durogesic) 12 (2U)',
  ]},
  { section: 'Analgesia / Corticoides / Procinéticos / Antieméticos', items: [
    'Ibuprofeno 400mg (5U)',
    'Ibuprofeno 2% (1U)',
    'Paracetamol 500mg (5U)',
    'Paracetamol gotas (1U)',
    'Metamizol (Metalgial) (1U)',
    'Dexametasona 1mg (Fortecortin) comp. (5U)',
    'Dexametasona 4mg (Fortecortin) comp. (5U)',
    'Prednisona (Dacortín) 30mg comp. (10U)',
    'Dexclorfeniramina (Polaramine) 2mg comp. (5U)',
    'Movicol pediátrico sobres (6U)',
    'Micralax (2U)',
    'Fisioenema 250 ml',
    'Ondansetrón (Setofilm) 4mg (10U)',
  ]},
  { section: 'Vía endovenosa (Opiáceos/BZD/Neurolépticos)', items: [
    'Cloruro mórfico 10mg/ml (10U)',
    'Fentanilo 0,15mg/3ml (5U)',
    'Metadona 10mg/ml (5U)',
    'Naloxona 0,4mg (2U)',
    'Midazolam 5mg/ml (10U)',
    'Flumacenilo (Anexate) 0,5mg/5ml (2U)',
    'Haloperidol 5mg (5U)',
    'Clorpromacina (Largactil) 25mg/5ml (2U)',
    'Ketamina 500mg/10ml (1U)',
    'Butilbromuro de escopolamina (Buscapina) 20mg (3U)',
    'Atropina 1mg/ml (3U)',
    'Dexdor 10 mcg/ml 2ml (3U)',
    'Clonidina 150 mcg/ml 1ml (5U)',
  ]},
  { section: 'Vía endovenosa (Varios)', items: [
    'Hidrocortisona (Actocortina) 100mg (3U)',
    'Dexametasona (Fortecortin) 4mg IV (5U)',
    'Adrenalina 1mg (10U)',
    'Amchafibrin 500mg (2U)',
    'Ceftriaxona 1g IM (2U)',
    'Lidocaína 1% (3U)',
    'Fenobarbital (Luminal) 200mg (5U)',
    'Levetiracetam (Keppra) 100mg/ml (4U)',
    'Ácido Valproico 500mg / 5ml (Depakine) (4U)',
    'Omeprazol 40mg (2U)',
    'Dexclorfeniramina (Polaramine) 5mg (3U)',
    'Furosemida (Seguril) 20mg (2U)',
    'Diazepam (Valium) 10mg (3U)',
    'Ondansetrón (Zofran) 8mg (2U)',
    'Metamizol (Nolotil) 2g/5ml (2U)',
    'Propofol 1% vol 50ml',
  ]},
];

// Catálogo ENFERMERÍA
window.CATALOG_ENFERMERIA = [
  { section: 'Bolsillo exterior', items: [
    'Fonendo (1)',
    'Bolsas residuos (5)',
    'Bolsas muestras (3)',
    'Pegatinas para fármacos',
    'Guantes no estériles',
    'Gel hidroalcohólico',
    'Pulsioxímetro + sensores (3)',
    'Mascarillas (5)',
    'Tarjetas visitas',
    'Bolígrafo',
    'Rotulador',
    'Empapadores (2)',
  ]},
  { section: 'Pruebas diagnósticas', items: [
    'Torundas para frotis (3U)',
    'Aspirado bronquial (2U)',
    'Bote copro (1U)',
    'Bote orina (1U)',
    'Tiras de orina',
    'Bolsa colectora de orina grande (1U)',
    'Sondas vesicales intermitentes CH 12 (2U) y CH 8 (2U)',
    'Sondas vesicales CH 6, 8, 10 (2U x N), 12, 14, 16 (1U x N)',
    'Jeringa cono ancho 60cc (1U)',
    'Sondas de aspiración CH 6, 10, 12, 16 (2U x N)',
    'Cánula Yankauer (1)',
  ]},
  { section: 'Analítica', items: [
    'Palomillas vacutainer (4U)',
    'Compresor (1U)',
    'Campana para vías (2U)',
    'Campana para palomillas (2U)',
    'Toallitas clorhexidina (5U)',
    'Tubos coag (2), hemog (2), Bq (2)',
    'Hemocultivos aerobio, anaerobio (1U)',
  ]},
  { section: 'Parenteral - Desinfectantes', items: [
    'Palomitas sub automática (2U), convencionales (2U)',
    'Abbocath 22 (2U), 24 (2U)',
    'Gripper 22G: 19 (2U), 25 (2U), 32 (2U)',
    'Alargadera PCA (1U)',
    'Agujas I/V, Sub, I/M (5U x bolsa), Carga (5U)',
    'Jeringas 1cc, 2cc, 5cc, 10cc (5U x tamaño) y 20cc (2U)',
    'Alargaderas (1U)',
    'Tapones azules / rojos / verdes',
    'Llaves de 3 pasos (2U)',
    'Jeringa 60cc (2U)',
    'Sistema pinchar PCA (1U)',
    'Sistema suero (1U)',
    'Clorhexidina acuosa (3U)',
    'Clorhexidina alcohólica (3U)',
    'Povidona Yodada (3U)',
  ]},
  { section: 'Nutrición enteral', items: [
    'Sondas de nutrición Ch 6, 8 (2U x N)',
    'Sondas de nutrición 10, 12 (1U x N)',
    'Jeringas enteral 60cc (1U), 20cc (2U), 10cc (2U), 5cc (2U), 1cc (4U)',
    'Conexiones de purés (1U) y de medicación (1U)',
    'Cepillos (2)',
    'Cono morado para cargar medicación (2)',
    'Agua destilada (5U)',
    'Esparadrapo marrón estrecho (1U)',
  ]},
  { section: 'Curas (Enf)', items: [
    'Bata (1U)',
    'Paños estériles (4U)',
    'Guantes estériles (3U)',
    'Bisturís (6U)',
    'Apósitos gasa pequeño/mediano/grande (10U x tamaño)',
    'Apósitos transparentes 5U Med, 5U grandes',
    'Apósito hidrocoloide (2U)',
    'Apósitos de espuma (2U)',
    'Hidrotac (2)',
    'Hidroclean (2)',
    'Apósitos alginato (2U)',
    'Apósito de silicona (4U)',
    'Steri-strip grandes (5U)',
    'Mefix',
    'Mepitac (1)',
    'Espongostan en lámina (1U)',
    'Parafina (5U)',
  ]},
  { section: 'Sueros', items: [
    'Cloruro NA 0,9% 100cc (1U)',
    'Cloruro NA 0,9% 50cc (2U)',
    'Cloruro NA 0,9% 10cc (10U)',
    'Gasas estériles (10)',
  ]},
  { section: 'Respiratorio (Enf)', items: [
    'Sensores pulsi (2)',
    'Gafas nasales pediátricas (1)',
    'Gafas nasales neonatales (1)',
    'Mascarilla reservorio P',
    'Mascarilla reservorio A',
    'Mascarilla aerosolterapia P y A (1)',
  ]},
  { section: 'Pomadas', items: [
    'Eliminador adhesivo spray',
    'Argenpal',
    'Crema barrera con óxido de zinc',
    'Emla',
    'Cloretilo',
    'Lubricante U',
    'Vaselina',
    'Ácidos grasos',
    'Diprogenta',
    'Diproderm',
    'Prontosan',
    'Flammazine',
    'Fucidine',
    'Hidrogel',
  ]},
  { section: 'Medicación I/V', items: [
    'Morfina (5 amp)',
    'Adrenalina (5 amp)',
    'Amchafibrin (2 amp)',
    'Lidocaína 1% (1 amp)',
    'Lidocaína 2% (1 amp)',
    'Haloperidol (2 amp)',
    'Polaramine (1 amp)',
    'Hidrocortisona (1 amp)',
    'Fibrilin (3 amp)',
    'Uroquinasa (1 amp)',
    'SRO hiposódico (1 sobre)',
    'Ondansetrón (5 comp)',
  ]},
  { section: 'Esparadrapos / Vendas', items: [
    'Esparadrapo pequeño',
    'Esparadrapo mediano',
    'Esparadrapo grande',
    'Venda cohesiva',
    'Venda de gasa',
  ]},
  { section: 'Tensiómetro / Otros', items: [
    'Pilas AA',
    'Metro',
    'Termómetro',
    'Glucómetro',
    'Lancetas (3U)',
  ]},
];

// Personas
window.MEDICOS = ['Alvaro', 'Lucía', 'Verónica', 'Julia', 'Iñigo', 'Bea', 'Dorleta'];
window.ENFERMERAS = ['Choni', 'Marta', 'Ana', 'Laura', 'Elena', 'Rocío', 'Carmen'];

// Convención de email usada por Firebase Auth y los scripts de seed.
// Normaliza acentos y toma el primer nombre → "Cristina Moya" → "cristina@ucp.local".
window.emailForUser = function (name) {
  const norm = (name || '')
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .split(/\s+/)[0];
  return `${norm}@ucp.local`;
};

// bagId estable por persona. Coherente con el seed de bags.
window.bagIdForUser = function (name, role) {
  const norm = (name || '')
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .split(/\s+/)[0];
  const prefix = role === 'medico' ? 'med' : role === 'enfermera' ? 'enf' : null;
  return prefix ? `${prefix}-${norm}` : null;
};
